/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._dam07;

import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.Color;

/**
 *
 * @author josam
 */
public class ComboRGB extends javax.swing.JFrame {

    /**
     * Creates new form ComboRGB
     */
    public ComboRGB() {
        initComponents();
        rellenarComboBox(ComboBoxRojo);
        rellenarComboBox(ComboBoxVerde);
        rellenarComboBox(ComboBoxAzul);
        rellenarComboBox(ComboBoxRojo1);
        rellenarComboBox(ComboBoxVerde1);
        rellenarComboBox(ComboBoxAzul1);
    }
    
    private void rellenarComboBox(JComboBox combo){
        for(int f=0; f<=255; f++){
            combo.addItem(String.valueOf(f));
        }
    }
    
    private void pintarBoton(JButton boton, JComboBox comboR, JComboBox comboG, JComboBox comboB){
        String cad1 = (String)comboR.getSelectedItem();
        String cad2 = (String)comboG.getSelectedItem();
        String cad3 = (String)comboB.getSelectedItem();
        int rojo = Integer.parseInt(cad1);
        int verde = Integer.parseInt(cad2);
        int azul = Integer.parseInt(cad3);
        Color color = new Color(rojo, verde, azul);
        boton.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlColorBoton = new javax.swing.JPanel();
        lblRojo = new javax.swing.JLabel();
        lblVerde = new javax.swing.JLabel();
        lblAzul = new javax.swing.JLabel();
        ComboBoxRojo = new javax.swing.JComboBox<>();
        ComboBoxVerde = new javax.swing.JComboBox<>();
        ComboBoxAzul = new javax.swing.JComboBox<>();
        pnlColorPanel = new javax.swing.JPanel();
        lblRojo1 = new javax.swing.JLabel();
        ComboBoxRojo1 = new javax.swing.JComboBox<>();
        lblVerde1 = new javax.swing.JLabel();
        ComboBoxVerde1 = new javax.swing.JComboBox<>();
        lblAzul1 = new javax.swing.JLabel();
        ComboBoxAzul1 = new javax.swing.JComboBox<>();
        btnColor1 = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Selecciona un color RGB");

        lblRojo.setText("Rojo:");

        lblVerde.setText("Verde:");

        lblAzul.setText("Azul:");

        javax.swing.GroupLayout pnlColorBotonLayout = new javax.swing.GroupLayout(pnlColorBoton);
        pnlColorBoton.setLayout(pnlColorBotonLayout);
        pnlColorBotonLayout.setHorizontalGroup(
            pnlColorBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColorBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlColorBotonLayout.createSequentialGroup()
                        .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlColorBotonLayout.createSequentialGroup()
                        .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlColorBotonLayout.createSequentialGroup()
                        .addComponent(lblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlColorBotonLayout.setVerticalGroup(
            pnlColorBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorBotonLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlColorBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRojo)
                    .addComponent(ComboBoxRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlColorBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerde))
                .addGap(21, 21, 21)
                .addGroup(pnlColorBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAzul))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlColorPanel.setLayout(new java.awt.GridLayout(3, 2));

        lblRojo1.setText("Rojo:");
        pnlColorPanel.add(lblRojo1);

        pnlColorPanel.add(ComboBoxRojo1);

        lblVerde1.setText("Verde:");
        pnlColorPanel.add(lblVerde1);

        pnlColorPanel.add(ComboBoxVerde1);

        lblAzul1.setText("Azul:");
        pnlColorPanel.add(lblAzul1);

        pnlColorPanel.add(ComboBoxAzul1);

        btnColor1.setText("Pintar botón");
        btnColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor1ActionPerformed(evt);
            }
        });

        btnColor.setText("Pintar botón");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlColorBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnColor)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pnlColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnColor1)
                                .addGap(59, 59, 59))))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColorBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnColor1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnColor)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        // TODO add your handling code here:
        pintarBoton(btnColor, ComboBoxRojo, ComboBoxVerde, ComboBoxAzul);
    }//GEN-LAST:event_btnColorActionPerformed

    private void btnColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor1ActionPerformed
        // TODO add your handling code here:
        pintarBoton(btnColor1, ComboBoxRojo1, ComboBoxVerde1, ComboBoxAzul1);
    }//GEN-LAST:event_btnColor1ActionPerformed

    private void comboBoxRojoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboRGB().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxAzul;
    private javax.swing.JComboBox<String> ComboBoxAzul1;
    private javax.swing.JComboBox<String> ComboBoxRojo;
    private javax.swing.JComboBox<String> ComboBoxRojo1;
    private javax.swing.JComboBox<String> ComboBoxVerde;
    private javax.swing.JComboBox<String> ComboBoxVerde1;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnColor1;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JLabel lblAzul1;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JLabel lblRojo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerde;
    private javax.swing.JLabel lblVerde1;
    private javax.swing.JPanel pnlColorBoton;
    private javax.swing.JPanel pnlColorPanel;
    // End of variables declaration//GEN-END:variables
}
