/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._dam07;

/**
 *
 * @author josam
 */
public class EjercicioPropuesto8 extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioPropuesto8
     */
    public EjercicioPropuesto8() {
        initComponents();
    }
    
    public void cambioTamano(String textoBtn){
        String[] textoBoton = textoBtn.split("x");
        String anchoStr = textoBoton[0];
        String altoStr = textoBoton[1];
        int ancho = Integer.parseInt(anchoStr);
        int alto = Integer.parseInt(altoStr);
        setSize(ancho,alto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTamanos = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        rbMin = new javax.swing.JRadioButton();
        rbMed = new javax.swing.JRadioButton();
        rbGran = new javax.swing.JRadioButton();
        rbMax = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Elige un tamaño para tu ventana");

        btnGroupTamanos.add(rbMin);
        rbMin.setText("640x840");
        rbMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CambioTamano(evt);
            }
        });

        btnGroupTamanos.add(rbMed);
        rbMed.setText("800x600");
        rbMed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CambioTamano(evt);
            }
        });

        btnGroupTamanos.add(rbGran);
        rbGran.setText("1024x768");
        rbGran.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CambioTamano(evt);
            }
        });

        btnGroupTamanos.add(rbMax);
        rbMax.setText("1920x1080");
        rbMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CambioTamano(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbGran, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbMax, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(27, 27, 27)
                .addComponent(rbMin)
                .addGap(18, 18, 18)
                .addComponent(rbMed)
                .addGap(18, 18, 18)
                .addComponent(rbGran)
                .addGap(18, 18, 18)
                .addComponent(rbMax)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambioTamano(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CambioTamano
        // TODO add your handling code here:
        if (rbMin.isSelected())
            cambioTamano(rbMin.getText());
        
        if (rbMed.isSelected())
            cambioTamano(rbMed.getText());
        
        if (rbGran.isSelected())
            cambioTamano(rbGran.getText());
        
        if (rbMax.isSelected())
            cambioTamano(rbMax.getText());
    }//GEN-LAST:event_CambioTamano

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioPropuesto8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTamanos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbGran;
    private javax.swing.JRadioButton rbMax;
    private javax.swing.JRadioButton rbMed;
    private javax.swing.JRadioButton rbMin;
    // End of variables declaration//GEN-END:variables
}
